# Generated by Django 3.1.1 on 2020-09-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('async_notifications', '0007_newsletter_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettertemplate',
            name='file_path',
        ),
    ]
